In [ ]:
!pip install --pre pycaret

In [ ]:
!gdown --id 1cijWpm7_S80zrRUJsBhTFk9btQYXuRHv

/usr/local/lib/python3.7/dist-packages/gdown/cli.py:131: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  category=FutureWarning,
Downloading...
From: https://drive.google.com/uc?id=1cijWpm7_S80zrRUJsBhTFk9btQYXuRHv
To: /content/launchit.csv
100% 53.0M/53.0M [00:00<00:00, 161MB/s]

In [ ]:
# read the csv file
import pandas as pd

data = pd.read_csv('launchit.csv')
data['Date'] = pd.to_datetime(data['Date'])
data.head()

,Date,Open,High,Low,Close,Adj Close,Volume,TCKR,sector,industry,country,growth_rate,target_median_price,target_mean_price,target_high_price
0,2019-12-19,11.000,11.96,10.50,10.70,10.70,89400.0,INDO,Energy,Oil & Gas E&P,Indonesia,1.206,15.0,15.0,15.0
1,2019-12-20,10.808,12.49,9.25,9.65,9.65,503000.0,INDO,Energy,Oil & Gas E&P,Indonesia,1.206,15.0,15.0,15.0
2,2019-12-23,8.790,8.79,7.25,7.81,7.81,117400.0,INDO,Energy,Oil & Gas E&P,Indonesia,1.206,15.0,15.0,15.0
3,2019-12-24,7.500,7.64,6.00,6.41,6.41,102800.0,INDO,Energy,Oil & Gas E&P,Indonesia,1.206,15.0,15.0,15.0
4,2019-12-26,6.420,7.72,6.42,7.41,7.41,78400.0,INDO,Energy,Oil & Gas E&P,Indonesia,1.206,15.0,15.0,15.0

In [ ]:
data.dtypes

Date                   datetime64[ns]
Open                          float64
High                          float64
Low                           float64
Close                         float64
Adj Close                     float64
Volume                        float64
TCKR                           object
sector                         object
industry                       object
country                        object
growth_rate                   float64
target_median_price           float64
target_mean_price             float64
target_high_price             float64
dtype: object

In [ ]:
# data['industry'] = pd.to_numeric(data['industry'],errors = 'coerce')

# Label Encode non-numeric columns
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
data['industry'] = le.fit_transform(data['industry'])

In [ ]:
data.dtypes

Date                   datetime64[ns]
High                          float64
Low                           float64
Close                         float64
Adj Close                     float64
Volume                        float64
sector                         object
industry                        int64
country                        object
growth_rate                   float64
target_median_price           float64
target_mean_price             float64
target_high_price             float64
time_series                    object
dtype: object

In [ ]:
data.head()

,Date,Open,High,Low,Close,Adj Close,Volume,TCKR,sector,industry,country,growth_rate,target_median_price,target_mean_price,target_high_price
0,2019-12-19,11.000,11.96,10.50,10.70,10.70,89400.0,INDO,Energy,59,Indonesia,1.206,15.0,15.0,15.0
1,2019-12-20,10.808,12.49,9.25,9.65,9.65,503000.0,INDO,Energy,59,Indonesia,1.206,15.0,15.0,15.0
2,2019-12-23,8.790,8.79,7.25,7.81,7.81,117400.0,INDO,Energy,59,Indonesia,1.206,15.0,15.0,15.0
3,2019-12-24,7.500,7.64,6.00,6.41,6.41,102800.0,INDO,Energy,59,Indonesia,1.206,15.0,15.0,15.0
4,2019-12-26,6.420,7.72,6.42,7.41,7.41,78400.0,INDO,Energy,59,Indonesia,1.206,15.0,15.0,15.0

In [ ]:
# combine TCKR and ADj Close column as time_series
data['TCKR'] = ['TCKR_' + str(i) for i in data['TCKR']]
data['Open'] = ['Open_' + str(i) for i in data['Open']]
data['time_series'] = data[['TCKR', 'Open']].apply(lambda x: '_'.join(x), axis=1)
data.drop(['TCKR', 'Open'], axis=1, inplace=True)

KeyError: ignored

In [ ]:
data.head()

,Date,High,Low,Close,Adj Close,Volume,sector,industry,country,growth_rate,target_median_price,target_mean_price,target_high_price,time_series
0,2019-12-19,11.96,10.50,10.70,10.70,89400.0,Energy,59,Indonesia,1.206,15.0,15.0,15.0,TCKR_INDO_Open_11.0
1,2019-12-20,12.49,9.25,9.65,9.65,503000.0,Energy,59,Indonesia,1.206,15.0,15.0,15.0,TCKR_INDO_Open_10.80799961090088
2,2019-12-23,8.79,7.25,7.81,7.81,117400.0,Energy,59,Indonesia,1.206,15.0,15.0,15.0,TCKR_INDO_Open_8.789999961853027
3,2019-12-24,7.64,6.00,6.41,6.41,102800.0,Energy,59,Indonesia,1.206,15.0,15.0,15.0,TCKR_INDO_Open_7.5
4,2019-12-26,7.72,6.42,7.41,7.41,78400.0,Energy,59,Indonesia,1.206,15.0,15.0,15.0,TCKR_INDO_Open_6.420000076293945

In [ ]:
data.dtypes

Date                   datetime64[ns]
Open                          float64
High                          float64
Low                           float64
Close                         float64
Adj Close                     float64
Volume                        float64
sector                         object
country                        object
growth_rate                   float64
target_median_price           float64
target_mean_price             float64
target_high_price             float64
time_series                    object
dtype: object

In [ ]:
# extract features from date
data['month'] = [i.month for i in data['Date']]
data['year'] = [i.year for i in data['Date']]
data['day_of_week'] = [i.dayofweek for i in data['Date']]
data['day_of_year'] = [i.dayofyear for i in data['Date']]
data.head()

,Date,Open,High,Low,Close,Adj Close,Volume,sector,country,growth_rate,target_median_price,target_mean_price,target_high_price,time_series,month,year,day_of_week,day_of_year
0,2019-12-19,11.000,11.96,10.50,10.70,10.70,89400.0,Energy,Indonesia,1.206,15.0,15.0,15.0,TCKR_INDO_industry_59,12,2019,3,353
1,2019-12-20,10.808,12.49,9.25,9.65,9.65,503000.0,Energy,Indonesia,1.206,15.0,15.0,15.0,TCKR_INDO_industry_59,12,2019,4,354
2,2019-12-23,8.790,8.79,7.25,7.81,7.81,117400.0,Energy,Indonesia,1.206,15.0,15.0,15.0,TCKR_INDO_industry_59,12,2019,0,357
3,2019-12-24,7.500,7.64,6.00,6.41,6.41,102800.0,Energy,Indonesia,1.206,15.0,15.0,15.0,TCKR_INDO_industry_59,12,2019,1,358
4,2019-12-26,6.420,7.72,6.42,7.41,7.41,78400.0,Energy,Indonesia,1.206,15.0,15.0,15.0,TCKR_INDO_industry_59,12,2019,3,360

In [ ]:
# check the unique time_series
data['time_series'].nunique()

547

In [ ]:
# plot multiple time series with moving avgs in a loop
import plotly.express as px
for i in data['time_series'].unique():
    subset = data[data['time_series'] == i]
    subset['moving_average'] = subset['Adj Close'].rolling(30).mean()
    fig = px.line(subset, x="Date", y=["Adj Close","moving_average"], title = i, template = 'plotly_dark')
    fig.show()

Output hidden; open in https://colab.research.google.com to view.